version: '3'
services:

  app:
    build: docker
    container_name: garden
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./framework:/var/www/html
      - ./log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./docker/php/20-xdebug.ini:/usr/local/etc/php/conf.d/zz-docker-php-ext-xdebug.ini
    env_file:
      - .env
    networks:
      - internal

  # dev mysql db:
  db:
    image: mysql:5.7
    container_name: gardendb
    working_dir: /dump
    volumes:
      - ./log:/var/log/mysql
      - ./docker/dump:/dump
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28